# Generated by Django 2.2.7 on 2019-12-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='squirrel',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Unique_squirrel_ID',
            field=models.CharField(help_text='Concatenation of Hectare(after deleting starting 0s) + Shift + first four digits of Date + Hectare squirrel number (after adding 0 in the bgeinning)', max_length=20),
        ),
    ]
