# Generated by Django 2.2.7 on 2019-12-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel_tracker', '0002_auto_20191204_0626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirrel',
            name='id',
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Unique_squirrel_ID',
            field=models.CharField(help_text='Concatenation of Hectare(after deleting starting 0s) + Shift + first four digits of Date + Hectare squirrel number (after adding 0 in the bgeinning)', max_length=20, primary_key=True, serialize=False),
        ),
    ]
