# Generated by Django 2.2.7 on 2019-12-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel_tracker', '0003_auto_20191204_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Date',
            field=models.IntegerField(blank=True, help_text='Date of the sighting', null=True),
        ),
    ]
