# Generated by Django 2.2.7 on 2019-12-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel_tracker', '0004_auto_20191205_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Approaches',
            field=models.BooleanField(default=False, help_text='True if the Squirrel is seen approaching human;otherwise False'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Chasing',
            field=models.BooleanField(default=False, help_text='True if squirrel was seen chasing;otherwise False'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Climbing',
            field=models.BooleanField(default=False, help_text='True if Squirrel was seen climbing;otherwise False'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Eating',
            field=models.BooleanField(default=False, help_text='True if Squirrel is Eating; otherwise False'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Foraging',
            field=models.BooleanField(default=False, help_text='True if Squirrel is Foraging; otherwise False'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Indifferent',
            field=models.BooleanField(default=False, help_text='True if squirrel was indifferent to Human; otherwise False'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Kuks',
            field=models.BooleanField(default=False, help_text='True if the Squirrel is kuking,a chirpy voice communication; otherwise False'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Moans',
            field=models.BooleanField(default=False, help_text='True if the Squirrel is Moaning,a high pitched vocal communication; otherwise False'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Quaas',
            field=models.BooleanField(default=False, help_text='True if the Squirrel is Quaaing,an elongated vocal call; otherwise False'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Running',
            field=models.BooleanField(default=False, help_text='True if squirrel seen running; otherwise False'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Runs_from',
            field=models.BooleanField(default=False, help_text='True if Squirrel was seen running from humans; otherwise false'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Tail_flags',
            field=models.BooleanField(default=False, help_text='True if the Squirrel is flagging its tail; otherwise False'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Tail_twitching',
            field=models.BooleanField(default=False, help_text='True if the Squirrel is twitching its tail; otherwise False'),
        ),
    ]
