# Generated by Django 2.2.7 on 2019-12-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel_tracker', '0005_auto_20191205_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Shift',
            field=models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Indication whether the sighting occurred in the afterrnoon or evening', max_length=10),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='X',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Longitutde of sighting', max_digits=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Y',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Latitude of sighting', max_digits=20),
        ),
    ]
